[package]
name = "serde_urlencoded"
version = "0.7.1" # bump in documentation link and in README on update
authors = ["Anthony Ramine <n.oxyde@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/bloom42/stdx"
documentation = "https://docs.rs/serde_urlencoded/0.7.1/serde_urlencoded/"
description = "`x-www-form-urlencoded` meets Serde"
categories = ["encoding", "web-programming"]
keywords = ["serde", "serialization", "urlencoded"]
exclude = ["/.travis.yml", "/bors.toml"]
edition = "2024"

[badges]
travis-ci = {repository = "nox/serde_urlencoded"}

[lib]
test = false

[dependencies]
form_urlencoded = { path = "../form_urlencoded" }
itoa = { path = "../itoa" }
ryu = { path = "../ryu" }

serde = { workspace = true }

# [dev-dependencies]
# serde_derive = "1"
