[package]
name = "hyper_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
pin-project-lite = { path = "../pin_project_lite" }

bytes = { workspace = true }
futures-util = { workspace = true }
hyper = { workspace = true }
tokio = { workspace = true }
