[package]
name = "thiserror"
version = "1.0.61"
authors = ["David Tolnay <dtolnay@gmail.com>"]
categories = ["rust-patterns"]
description = "derive(Error)"
documentation = "https://docs.rs/thiserror"
edition = "2024"
keywords = ["error", "error-handling", "derive"]
license = "Apache-2.0"
repository = "https://github.com/bloom42/stdx"
rust-version = "1.85"

[dependencies]
thiserror-impl = { path = "impl" }

[dev-dependencies]
# anyhow = "1.0.73"
# ref-cast = "1.0.18"
# rustversion = "1.0.13"
# trybuild = { version = "1.0.81", features = ["diff"] }

#[workspace]
#members = ["impl"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--generate-link-to-definition"]
