[package]
name = "bel_benchmarks"
version = "0.11.0"
edition = "2024"
license = "MIT"

[dev-dependencies]
bel = { path = ".." }

criterion = { version = "0.5", features = ["html_reports"] }
# dhat = { version = "0.3" }


[[bench]]
name = "runtime"
harness = false


[profile.bench]
lto = true
codegen-units = 1
opt-level = 3
# Line numbers for dhat
debug = 1

