[package]
name = "unsafe_libyaml"
version = "0.2.11"
authors = ["David Tolnay <dtolnay@gmail.com>"]
categories = ["encoding", "parser-implementations", "no-std"]
description = "libyaml transpiled to rust by c2rust"
documentation = "https://docs.rs/unsafe-libyaml"
edition = "2024"
keywords = ["yaml"]
license = "MIT"
repository = "https://github.com/bloom42/stdx"
rust-version = "1.85"

# [workspace]
# [dev-dependencies]
# pretty_assertions = "1.0"
# unsafe-libyaml-test-suite = { path = "tests/data" }

[lib]
doc-scrape-examples = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--generate-link-to-definition"]
