[package]
name = "bel_examples"
version = "0.1.0"
edition = "2024"

[features]
axum = ["dep:axum", "dep:tokio", "dep:thiserror"]
json = ["dep:serde_json", "bel/json"]
time = ["dep:chrono", "bel/time"]
anyhow = ["dep:anyhow"]
regex = ["bel/regex"]
ip = ["bel/ip"]

[dependencies]
bel = { path = "..", default-features = false }

chrono = { version = "0.4", optional = true }

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }

axum = { version = "0.7.5", default-features = false, features = [
    "http1",
    "json",
    "tokio",
], optional = true }
tokio = { version = "1.38.0", default-features = false, features = [
    "macros",
    "net",
    "rt-multi-thread",
], optional = true }
thiserror = { version = "1.0", optional = true }
anyhow = { version = "1.0.98", optional = true }

[[bin]]
name = "simple"
path = "src/simple.rs"
required-features = ["regex"]

[[bin]]
name = "variables"
path = "src/variables.rs"

[[bin]]
name = "functions"
path = "src/functions.rs"
required-features = ["time"]

[[bin]]
name = "threads"
path = "src/threads.rs"

[[bin]]
name = "serde"
path = "src/serde.rs"

[[bin]]
name = "axum"
path = "src/axum.rs"
required-features = ["axum"]

[[bin]]
name = "json"
path = "src/json.rs"
required-features = ["json"]

[[bin]]
name = "anyhow"
path = "src/anyhow.rs"
required-features = ["anyhow"]


[[bin]]
name = "ip"
path = "src/ip.rs"
required-features = ["ip"]
